name: Pipeline test

on:
  push:
    branches:
      - main

jobs:
  validar-push-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar se existe pelo menos um html
        run: |
          if find . -name "*.html" | grep -q .; then 
            echo "Arquivos HTML encontrados com sucesso."
          else 
            echo "Nenhum arquivo HTML encontrado."
            exit 1
          fi
